### ISSUE TITLE
[Feat] 도서 상세보기 뷰 구현

### ISSUE THREAD

**Issue by 6uohul** [SOPT-TEAM6-Aladin/Aladin-iOS#5]
## 🛠 Issue

도서 상세보기 뷰 구현

## 📝 To-do

- [x] 상세보기 파일 생성
- [x]  전체 스크롤 뷰 구현
- [x] 네비 UIView 구현
- [x] ContainerView로 각각 구현
- [x] 장바구니 구매하기 UIView 구현
