### ISSUE TITLE
[Feat] 메인 뷰 구현

### ISSUE THREAD

**Issue by zzongha** [SOPT-TEAM6-Aladin/Aladin-iOS#6]
## 🛠 Issue

메인 뷰 구현

## 📝 To-do

- [x] 전체 스크롤 뷰 구현
- [x] ContainerView로 크게 영역 나눠서 구현
- [x] 서치바 구현
- [x] 헤더 이미지 UIView 구현
- [x] 카테고리 아이콘 UIStackView 구현
- [x] 편집장의 선택 CollectionView 구현
- [ ] 지금, 화제의 책! CollectionView 구현
- [x] 나머지 부분 UILabel, UIButton, UIView 구현
